const OK = 200;
const ACCEPTED = 202;
const CREATED = 201;
const NO_CONTENT = 204;
const MOVED_PERMANENTLY = 301;
const NOT_MODIFIED = 304;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const UNPROCESSABLE_ENTITY = 422;
const INTERNAL_SERVER_ERROR = 500;
const NOT_IMPLEMENTED = 501;
const SERVICE_UNAVAILABLE = 503;

module.exports = {
    OK: OK,
    ACCEPTED: ACCEPTED,
    CREATED: CREATED,
    NO_CONTENT: NO_CONTENT,
    MOVED_PERMANENTLY: MOVED_PERMANENTLY,
    NOT_MODIFIED: NOT_MODIFIED,
    BAD_REQUEST: BAD_REQUEST,
    UNAUTHORIZED: UNAUTHORIZED,
    FORBIDDEN: FORBIDDEN,
    NOT_FOUND: NOT_FOUND,
    UNPROCESSABLE_ENTITY: UNPROCESSABLE_ENTITY,
    INTERNAL_SERVER_ERROR: INTERNAL_SERVER_ERROR,
    NOT_IMPLEMENTED: NOT_IMPLEMENTED,
    SERVICE_UNAVAILABLE: SERVICE_UNAVAILABLE
}